import type { DisplayLocation, Token, ValidationResult } from "./types.ts";
import * as webidl2 from "webidl2";

const INDENT = "    ";

/**
 * Parse a WebIDL string into an abstract syntax tree (AST). The
 * resulting AST can be passed to {@link format} or {@link validate}.
 *
 * @param idl      The WebIDL source code to parse.
 * @param source   An optional identifier used in error messages.
 * @throws Error   When the input contains syntax errors.
 */
export function parse(
  idl: string,
  source: string = "<anonymous>",
): webidl2.IDLRootType[] {
  try {
    const tree = webidl2.parse(idl, { sourceName: source });
    enrichTreeTokens(tree, idl);
    return tree;
  } catch (error) {
    enrichErrorLocationMetadata(error, idl);
    throw error;
  }
}

/**
 * Format WebIDL source code. This function parses the provided
 * string, applies any available autofixes exposed by the
 * underlying validator and then regenerates a canonical
 * representation from the AST. If parsing fails the
 * original input is returned untouched.
 *
 * @param idl      The WebIDL source code to format.
 * @param [source]   An optional filename used in diagnostic messages.
 * @returns        A formatted IDL string.
 */
export function format(
  idl: string,
  source: string = "<anonymous>",
  autofix: boolean = true,
): string {
  try {
    const tree = parse(idl, source);
    const results = webidl2.validate(tree) as ValidationResult[];
    for (const res of results) {
      enrichLocationMetadata(res);
      if (autofix) res.autofix?.();
    }
    const normalizedTree = parse(webidl2.write(tree), source);
    normalizeTokenTrivia(normalizedTree);
    return preserveFinalNewline(webidl2.write(normalizedTree), idl);
  } catch {
    // Propagate original content on error; callers can
    // separately inspect syntax errors using parse().
    return idl;
  }
}

/**
 * Validate an AST generated by {@link parse}. Returns an array of
 * validation problems. The array is empty when no semantic issues
 * are detected. The objects may contain an `autofix` function to
 * automatically apply recommended fixes to the AST.
 *
 * @param tree     The AST returned by {@link parse}.
 * @returns        A list of validation results.
 */
export function validate(
  tree: webidl2.IDLRootType | webidl2.IDLRootType[],
): ValidationResult[] {
  const results = webidl2.validate([tree].flat()) as ValidationResult[];
  for (const result of results) {
    enrichLocationMetadata(result);
  }
  return results;
}

/**
 * Convenience function that parses and validates a WebIDL string in
 * one step. If the input contains syntax errors an exception is
 * thrown. Semantic problems are returned as an array.
 *
 * @param idl      The WebIDL source code to validate.
 * @param [source] An optional filename used in error messages.
 * @returns        A list of validation results.
 */
export function validateIDL(
  idl: string,
  source: string = "<anonymous>",
): ValidationResult[] {
  const tree = parse(idl, source);
  return validate(tree);
}

function lineAndColumnFromIndex(
  offset: number,
  source: string,
): DisplayLocation {
  let line = 0, column = 0, displayLine = 1, displayColumn = 1;
  for (let i = 0; i < offset && i < source.length; i++) {
    const char = source[i];
    if (char === "\n" || char === "\r") {
      line += 1;
      column = 0;
      // Skip the next character since it's part of the \r\n sequence
      if (char === "\r" && source[i + 1] === "\n") i++;
    } else {
      column += 1;
    }
    displayLine = line + 1;
    displayColumn = column + 1;
  }
  return { line, column, offset, displayLine, displayColumn };
}

type SourceTokenArray = webidl2.Token[] & { name?: string };

interface SourceBackedNode {
  source?: SourceTokenArray;
}

function enrichTreeTokens(tree: webidl2.IDLRootType[], source: string): void {
  const sourceTokens = sourceTokensFromTree(tree);
  if (!sourceTokens) return;

  let cursor = 0;
  for (const token of sourceTokens) {
    const trivia = token.trivia ?? "";
    const value = token.value ?? "";

    let startOffset = cursor + trivia.length;
    let endOffset = startOffset + value.length;

    if (
      source.slice(cursor, startOffset) !== trivia ||
      source.slice(startOffset, endOffset) !== value
    ) {
      const recoveredOffset = recoverTokenOffset(token, source, cursor);
      startOffset = recoveredOffset;
      endOffset = startOffset + value.length;
    }

    enrichToken(token, source, startOffset, endOffset);
    cursor = Math.max(endOffset, cursor + trivia.length + value.length);
  }
}

function sourceTokensFromTree(
  tree: webidl2.IDLRootType[],
): SourceTokenArray | undefined {
  for (const node of tree as SourceBackedNode[]) {
    if (Array.isArray(node.source)) {
      return node.source;
    }
  }
}

function recoverTokenOffset(
  token: webidl2.Token,
  source: string,
  cursor: number,
): number {
  if (!token.value) return source.length;
  const afterTrivia = cursor + (token.trivia?.length ?? 0);
  const exact = source.indexOf(token.value, afterTrivia);
  if (exact >= 0) return exact;
  const fallback = source.indexOf(token.value, cursor);
  return fallback >= 0 ? fallback : Math.min(afterTrivia, source.length);
}

function enrichToken(
  token: webidl2.Token,
  source: string,
  startOffset: number,
  endOffset: number,
): void {
  const start = lineAndColumnFromIndex(startOffset, source);
  const end = lineAndColumnFromIndex(endOffset, source);
  const width = endOffset - startOffset, height = end.line - start.line;
  Object.assign(token, { start, end, width, height });
}

function enrichErrorLocationMetadata(error: unknown, source: string): void {
  if (!error || typeof error !== "object") return;
  const candidate = error as Partial<ValidationResult>;
  const tokens = candidate.tokens;
  if (!Array.isArray(tokens)) return;

  let cursor = lineStartOffset(
    tokens[0]?.line ?? candidate.line ?? 1,
    source,
  );
  for (const token of tokens) {
    const startOffset = recoverTokenOffset(token, source, cursor);
    const endOffset = startOffset + (token.value?.length ?? 0);
    enrichToken(token, source, startOffset, endOffset);
    cursor = endOffset;
  }

  enrichLocationMetadata(candidate as ValidationResult);
}

function lineStartOffset(oneBasedLine: number, source: string): number {
  if (!Number.isFinite(oneBasedLine) || oneBasedLine <= 1) {
    return 0;
  }
  let line = 1;
  for (let offset = 0; offset < source.length; offset++) {
    const char = source[offset];
    if (char === "\n" || char === "\r") {
      line += 1;
      if (char === "\r" && source[offset + 1] === "\n") offset++;
      if (line === oneBasedLine) {
        return offset + 1;
      }
    }
  }
  return source.length;
}

function enrichLocationMetadata(result: ValidationResult): void {
  const { tokens } = result;
  const enriched = result as ValidationResult;
  const token = tokens.find((token) => token.value || hasRange(token));
  if (!token || !hasRange(token)) return;

  enriched.start = token.start;
  enriched.end = token.end;
  enriched.width = token.width;
  enriched.height = token.height;
}

function hasRange(token: webidl2.Token): token is Token {
  const candidate = token as Partial<Token>;
  return !!candidate.start && !!candidate.end &&
    typeof candidate.width === "number" &&
    typeof candidate.height === "number";
}

function normalizeTokenTrivia(tree: webidl2.IDLRootType[]): void {
  const tokens = collectTokens(tree);
  let stache = 0, square = 0, parens = 0;

  let previous: webidl2.Token | undefined;

  for (const token of tokens) {
    const { value } = token;

    if (value === "}") stache -= 1;
    if (value === "]") square -= 1;
    if (value === ")") parens -= 1;

    token.trivia = triviaForToken(token, previous, stache, square);

    if (value === "{") stache += 1;
    if (value === "[") square += 1;
    if (value === "(") parens += 1;

    previous = token;
  }
}

function collectTokens(tree: webidl2.IDLRootType[]): webidl2.Token[] {
  const seen = {
    tokens: new WeakSet<webidl2.Token>(),
    objects: new WeakSet<object>(),
  };
  const tokens: webidl2.Token[] = [];

  (function visit(value: unknown): void {
    if (value && typeof value === "object" && !seen.objects.has(value)) {
      seen.objects.add(value);

      if (isToken(value)) {
        if (!seen.tokens.has(value)) {
          seen.tokens.add(value);
          tokens.push(value);
        }
      } else if (Array.isArray(value)) {
        if ("tokens" in value) visit(value.tokens);
        for (const item of value) visit(item);
      } else {
        const record = Object(value) as Record<string, unknown>;
        for (
          const key of [
            "tokens",
            "extAttrs",
            "members",
            "idlType",
            "arguments",
            "default",
            "value",
            "expression",
            "values",
            "rhs",
            "parent",
          ] as const
        ) key in record && visit(record[key]);

        for (const child of Object.values(record)) visit(child);
      }
    }
  })(tree);

  return tokens.sort((left, right) => left.index - right.index);
}

function isToken(it: unknown): it is webidl2.Token {
  const token = Object(it || {});
  return typeof token.type === "string" &&
    typeof token.value === "string" &&
    typeof token.trivia === "string" &&
    typeof token.line === "number" &&
    typeof token.index === "number";
}

function triviaForToken(
  token: webidl2.Token,
  previous: webidl2.Token | undefined,
  braces: number = 0,
  square: number = 0,
  parens: number = 0,
): string {
  const whitespace = whitespaceForToken(
    token,
    previous,
    braces,
    square,
    parens,
  );
  const commentDepth = token.value === "}" ? braces + 1 : braces;
  const comments = formatCommentsFromTrivia(token.trivia, commentDepth);
  if (!comments) {
    return whitespace;
  }
  const beforeComments = whitespace.includes("\n") ? "\n" : whitespace;
  return `${beforeComments}${comments}${INDENT.repeat(braces)}`;
}

function whitespaceForToken(
  token: webidl2.Token,
  previous: webidl2.Token | undefined,
  depth: number = 0,
  square: number = 0,
  _parens: number = 0,
): string {
  if (!token?.value || !previous?.value) return "";
  if (token.value === "}") return `\n${INDENT.repeat(depth)}`;
  if ((token.value === "[" || token.value === "{") && previous.value === "=") {
    return " ";
  }
  if (previous.value === ";" && depth === 0) return "\n\n";
  if (
    (previous.value === "]" && startsAttributedConstruct(token.value)) ||
    previous.value === ";" || previous.value === "{"
  ) return `\n${INDENT.repeat(depth)}`;

  if (
    token.value === "," ||
    token.value === ";" ||
    token.value === ")" ||
    token.value === "]" ||
    token.value === ">" ||
    token.value === "?" ||
    token.value === "<" ||
    token.value === "[" ||
    token.value === "(" ||
    token.value === "..." ||
    previous.value === "(" ||
    previous.value === "[" ||
    previous.value === "<"
  ) return "";

  if (previous.value === "," && depth > 0 && token.type === "string") {
    return `\n${INDENT.repeat(depth)}`;
  }
  if (
    previous.value === "," ||
    previous.value === "..." ||
    previous.value === ":" ||
    token.value === ":" ||
    token.value === "{"
  ) {
    return " ";
  }
  if (token.value === "=" || previous.value === "=") {
    return square > 0 ? "" : " ";
  }
  return " ";
}

const ATTRIBUTE_NAME_KEYWORDS = [
  "attribute",
  "callback",
  "const",
  "constructor",
  "deleter",
  "dictionary",
  "enum",
  "getter",
  "includes",
  "inherit",
  "interface",
  "iterable",
  "maplike",
  "namespace",
  "partial",
  "readonly",
  "setter",
  "setlike",
  "static",
  "stringifier",
  "typedef",
] as const;

function startsAttributedConstruct(value: string): boolean {
  return ATTRIBUTE_NAME_KEYWORDS.includes(value as never);
}

function preserveFinalNewline(formatted: string, original: string): string {
  const withoutFinalNewline = formatted.trimEnd();
  if (!hasFinalNewline(original)) return withoutFinalNewline;
  return `${withoutFinalNewline}${detectLineEnding(original)}`;
}

function detectLineEnding(text: string): "\r\n" | "\r" | "\n" {
  return text.match(/\r\n|\r|\n/)?.[0] as never || "\n";
}

function hasFinalNewline(text: string): boolean {
  return /(?:\r\n|\r|\n)$/.test((text || "") + "");
}

function formatCommentsFromTrivia(
  trivia: string | undefined,
  depth: number = 0,
): string {
  if (!trivia || !/\/[/*]/.test(trivia)) return "";
  const comments = trivia.match(/\/\/[^\r\n]*|\/\*[\s\S]*?\*\//g) ?? [];
  if (!comments.length) return "";
  return `${
    comments.map((comment) => {
      const normalized = comment.trimEnd();
      return `${INDENT.repeat(depth)}${normalized}`;
    }).join("\n")
  }\n`;
}
